name: CI
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      AUTH_PARAM_PATH: ${{ secrets.AUTH_PARAM_PATH }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Install tools from .tool-versions
        uses: asdf-vm/actions/install@v1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: lint
        run: pnpm lint
      